name: Robot Framework CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Install pip dependencies
          run: pip3 install -r requirements.txt
        - name: Install Task Warrior
          run: | 
              sudo apt-get install taskwarrior -y
              task rc.confirmation=off version
        - name: Run Test
          run: python -m robot --outputdir reports tests
        - name: Publish test reports
          uses: actions/upload-artifact@v2
          with:
            name: report.html
            path: reports/report.html

    # Generate-report:
    #     needs: [Run-Test]
    #     runs-on: ubuntu-20.04
    #     steps:
    #     - uses: actions/checkout@v2
    #     - name: Download reports
    #       uses: actions/download-artifact@v1
    #       with:
    #         name: reports
    #     - name: Send report to commit
    #       uses: joonvena/robotframework-reporter-action@v2
    #       with:
    #         gh_access_token: ${{ secrets.GITHUB_TOKEN }}
