name: Robot Framework CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Install pip dependencies
          run: pip3 install -r requirements.txt
        - name: Install Task Warrior
          run: | 
              sudo apt-get install taskwarrior -y
              task rc.confirmation=off version
        - name: Run Test
          run: python -m robot --outputdir results tests
        - name: Publish test results
          uses: actions/upload-artifact@v2
          with:
            name: robot-test-results
            path: results
